services:
  - type: web
    name: projeto-frota
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install gunicorn
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true